---
language: python
python: "2.7"
sudo: required
dist: trusty
services:
  - docker
env:
  global:
  - secure: "BUSjIlm+itTfSo8Ri5U7YzFP0J239SKCmHPmb/KoMSeLEFViUor2jSRRiZr9rdYFBOeYXNpN7BEifZBzNYLQ+eJZH4ra9kCjmlieON3z5vUsZCRylGNjs8nQ4T43n6i/gNJ7BjXSfKKKBJYp4ogEMSneu6UkKdA1BfwTyoRcDgOZcKS2chnEDakIxycwpLpNmEYNMRWYujEA785Anw+Qo/WnJpxGGBXngLRQJy7gKVaMg9MvIhMPHwL1FcuEScbLSfyIPZ1xjKNsn8ME6JXoXRndqX03F1e8jOmrEfghHTcaJdXp6MZ0mqlbnXCMLqn9IGTU2baiBl9/z6T5zAf5Z/GvsJM/V2AmU1RH/W93G/ulC2Qt9ruBUDJWULx3sSWqvR5TPSI0GccDO8YvgW5jrc3ia6k9POsw+DYbtIGU/ntZ65/ly5Ufir1XmJDWpujoJ9TsLKDLVXh7SL/Ejqm+mw9n6JNqBcucFs/fhjxWF8iGU7dMczmOBi5r/CHnIIA0l7cycAlVotGM+auvxY6NSThgikNFnrvZYDuVGr6dW4eQUHwPTEO/mm5IPYMoEymrV/ognjBi/S2WdRKm6sBLKzH3cALvRb+sqRqAHsbd1aH8fYdgIwzU6qHSlZPFhxn1FjgWf1CsgNPYXGfzGlRw+LWIZOBR7IE4U4vDJE70O/k="
  - secure: "P36ErXjHhANeOca2lYz6w0j48Qz+xcisFxzVf+jIuG9Rc6hC9H/q1cZ1nXHnGNhkjkg7L/hpldiMogakygqIsl8cqZvDrMLwzCjvPJTRGM0sxVUOmnfl8WDUmtkhZFkFT2JAMBGkYoxqvIcZuDBAXXwAaxJOB2KVY48nRun/XCwudN34gGAR9PwakWzYNuTSoTuXNFlI48cJVJ1PCVqcetpePZW+vpbzqKFNqdoZXW9KrzOBWb7kU5jCPzgiwR5Cehdf99IoODZWhpz4fzNAicViNFJHAk8LK4Mb55ydYIrm8WcmAess9a5yAx/WZCLWoStAWWng69aABNZZ9VdFIovaraONeV3Ol0Cfo4/IgYyvGh2f6EmkkBQhxEUmAP/hha3MV5YSxjPIXlybObphL3WKqZ4XCo4iT9efJS3nqRlyUgmIPC/ktOWcrIHGiHVFkiUvfWY0+6OEtXwSrJrVh7/Pp065rTohHWeqC7VKdHMddGqeeCeAqgu6zRcp+Wycc5DyRoOCCIozVMCcVqEIDilv8roQ5Xb+bQJCrUFA1seLUkwlvN1WjP9OP2jTDjroGYCSCbHKc69S25yYO4PtvJ3M5TtHEsGqwLpaJF+kYTmEb5H90VjZQCwqDGBWlqaE7Of0rczzpA89JOOl0tmnrBTGjOnc/zOo/WMPKA+190c="
git:
  submodules: false
before_install:
 - git submodule update --init --recursive
 - git submodule foreach git pull origin master
 - sudo apt-get update -qq
 - sudo apt-get install -qq squashfs-tools uuid python-apt python-pycurl btrfs-tools
install:
 - sudo pip install ansible
 - sudo pip install docker-py
script:
- cp -R roles/* squashible/roles/
- cp squashible.yml squashible/
- cd squashible
- sudo ansible-playbook -i hosts_generator.py squashible.yml -e "live_os=centos_7" -e "rootfs_size=8G"
- ls -lah live_output
- sudo chown -R travis:travis live_output
- cd live_output
after_success:
    "curl --ftp-create-dirs -T '{vmlinuz,initrd.img,rootfs.img,rootfs.img.torrent}' -u $FTP_USER:$FTP_PASSWORD ftp://images.squashible.com/images/ecopoiesis-utility-centos/"
