---

- name: Install EPEL RPM for CentOS 7
  shell: "{{item}}"
  with_items:
    - curl -so /tmp/epel-release-7-11.noarch.rpm http://mirrors.edge.kernel.org/fedora-epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
    - rpm -Uvh /tmp/epel-release-7-11.noarch.rpm
    - rm -f /tmp/epel-release-7-11.noarch.rpm
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == "7.4.1708"

- name: Install distro packages
  package:
    name: "{{ utility_distro_packages }}"
    state: latest

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ utility_pip_packages }}"

- name: Copy lldpd.conf to etc
  copy:
   src: lldpd.conf
   dest: /etc/lldpd.conf

- name: Checkout ecopoiesis-utility
  git:
    repo: https://github.com/antonym/ecopoiesis-utility
    dest: /opt/ecopoiesis-utility
    version: master
    depth: 1
    force: true

- name: Install ecopoiesis-utility startup
  copy:
    src: ecopoiesis-utility
    dest: /usr/local/bin/ecopoiesis-utility
    mode: 0744

- name: Install ecopoiesis-utility service file
  copy:
    src: ecopoiesis-utility.service
    dest: /lib/systemd/system/ecopoiesis-utility.service

- name: Enable systemd services
  file: src={{ item.path }} dest={{ item.dest }} state=link
  with_items:
    - { path: '/lib/systemd/system/ecopoiesis-utility.service', dest: '/etc/systemd/system/multi-user.target.wants/ecopoiesis-utility.service' }
    - { path: '/lib/systemd/system/lldpd.service', dest: '/etc/systemd/system/multi-user.target.wants/lldpd.service' }
    - { path: '/lib/systemd/system/NetworkManager.service', dest: '/etc/systemd/system/multi-user.target.wants/NetworkManager.service' }
