---
#
# Dell OpenManage Tooling - http://linux.dell.com/repo/community/ubuntu/
#

- name: Install Dell Openmanage apt key
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: 1285491434D8786F
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Dell Openmanage apt repository
  apt_repository:
    repo: deb http://linux.dell.com/repo/community/ubuntu xenial openmanage
    state: present
    filename: linux.dell.com.sources.list
  when: ansible_distribution == "Ubuntu"

- name: Install system updates for Ubuntu systems
  apt: upgrade=dist update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install Dell Openmanage packages
  package:
    name: "{{ item }}"
  with_items:
#    - srvadmin-base
    - srvadmin-idracadm8
    - srvadmin-idracadm7
  ignore_errors: true

#- name: Start Dell dataeng service
#  service:
#    name: dataeng
#    state: started
#    enabled: yes 
#  ignore_errors: yes
