---

utility_distro_packages:
  - gcc
  - git
  - iputils
  - openssl-devel
  - lldpd
  - NetworkManager
  - python-devel
  - python-pip
  - python-setuptools
  - uuid
  - vim
utility_pip_packages:
  - ansible
